version: 0.0
os: linux
files:
  - source: /
    destination: /var/app/current
hooks:
  BeforeInstall:
    - location: sudo yum install -y docker
      timeout: 300
      runas: root
  AfterInstall:
    - location: sudo chmod -R 755 /var/app/current
      timeout: 300
      runas: root
  ApplicationStart:
    - location: |
        docker pull shivamspace/chat:1
        docker stop chat-container || true
        docker rm chat-container || true
        docker run -d --name chat-container shivamspace/chat:1
      timeout: 300
      runas: root
  ApplicationStop:
    - location: |
        docker stop chat-container || true
        docker rm chat-container || true
      timeout: 300
      runas: root
